export default function TermsPage() {
  return (
    <div className="relative z-10 w-full max-w-2xl px-4 py-16">
      <h1
        className="text-3xl font-bold text-white mb-2"
        style={{ fontFamily: "'Georgia', serif", letterSpacing: "-0.03em" }}
      >
        Terms & Conditions
      </h1>
      <p className="text-white/30 text-sm mb-10">Last updated: March 2026</p>

      <div className="flex flex-col gap-8 text-white/60 text-sm leading-relaxed">
        <section>
          <h2 className="text-white/80 font-semibold mb-2">
            1. About the Service
          </h2>
          <p>
            Hey How Are You (
            <strong className="text-white/60">heyhowareyou.vercel.app</strong>)
            is an AI-powered tool that rates dating app opening messages. The
            service provides feedback and scores based on AI analysis. Results
            are for entertainment and informational purposes only.
          </p>
        </section>

        <section>
          <h2 className="text-white/80 font-semibold mb-2">
            2. Use of the Service
          </h2>
          <p>
            By using this service you agree to use it only for lawful purposes.
            You must not submit content that is offensive, abusive, or violates
            the rights of others. We reserve the right to suspend access to
            users who misuse the service.
          </p>
        </section>

        <section>
          <h2 className="text-white/80 font-semibold mb-2">3. Payments</h2>
          <p>
            Access to Top Openers is available for a one-time payment of $4.99
            USD, processed securely via Paddle. All payments are final and
            non-refundable unless required by applicable law. You will receive
            lifetime access to the Top Openers feature upon successful payment.
          </p>
        </section>

        <section>
          <h2 className="text-white/80 font-semibold mb-2">4. User Content</h2>
          <p>
            When you submit an opener and choose to make it public, you grant us
            a non-exclusive license to display it on the platform. You retain
            ownership of your content. We do not sell your content to third
            parties.
          </p>
        </section>

        <section>
          <h2 className="text-white/80 font-semibold mb-2">5. Privacy</h2>
          <p>
            We collect your email address and name via Google/Facebook
            authentication (powered by Clerk). We store your saved openers and
            payment status in our database. We do not sell your personal data to
            third parties. For more information see our Privacy Policy.
          </p>
        </section>

        <section>
          <h2 className="text-white/80 font-semibold mb-2">6. AI Disclaimer</h2>
          <p>
            Ratings and feedback are generated by AI and are not guaranteed to
            be accurate or effective. Results may vary. We are not responsible
            for outcomes of using openers on dating platforms.
          </p>
        </section>

        <section>
          <h2 className="text-white/80 font-semibold mb-2">
            7. Limitation of Liability
          </h2>
          <p>
            The service is provided &apos;as is&apos; without warranties of any
            kind. We are not liable for any damages arising from your use of the
            service, including but not limited to loss of data, revenue, or
            romantic opportunities.
          </p>
        </section>

        <section>
          <h2 className="text-white/80 font-semibold mb-2">
            8. Changes to Terms
          </h2>
          <p>
            We reserve the right to update these terms at any time. Continued
            use of the service after changes constitutes acceptance of the new
            terms.
          </p>
        </section>

        <section>
          <h2 className="text-white/80 font-semibold mb-2">9. Contact</h2>
          <p>
            For any questions regarding these terms please contact us at{" "}
            <strong className="text-white/60">heyhowareyou.vercel.app</strong>.
          </p>
        </section>
      </div>
    </div>
  );
}
